In [3]:
import pandas as pd
import numpy as np

## Key Data Structures In Pandas 
1. Series : Is a labeled Array
2. DataFrame

In [4]:
s = pd.Series([1,2,3,4],index=['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
df = pd.DataFrame({"Name":["Mehdi","Murtaza","Naqi"],
                   "Marks":[100,3,4]},index=['a','b','c'])

In [6]:
df

      Name  Marks
a    Mehdi    100
b  Murtaza      3
c     Naqi      4

In [7]:
csv = pd.read_csv("Ciphertronix employee and hardware details.xlsx - Employees Info.csv")

In [8]:
csv.head(5)

,EMPLOYEES INFORMATION,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Serial Number,Name,Date Of Birth,Father Name,Mother Name,Email ID,Phone Number,CNIC Number,Emergency Phone Number,Adress
2,1,Muhammad Shabaz Sharif,28th February 1980,NaN,NaN,Shahbaz@ciphertronix.com,0330-6861098,NaN,NaN,NaN
3,2,Ovais Khan,4th August 1996,NaN,NaN,ovais.khan@ciphertronix.com,0332-3188340,NaN,NaN,NaN
4,3,Syed Sibtain Raza,24th November 2000,Syed Raza Hussain,NaN,sibtain.raza@ciphertronix.com,0335-2840908,42101-7108936-9,NaN,NaN

In [9]:
csv.tail(5)

,EMPLOYEES INFORMATION,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
12,11,Mohammad Hammad,NaN,NaN,NaN,mhammad352424@gmail.com,0342-2023191,NaN,NaN,"House#129, S-1, Shahwaliuallah Nagar, Orangi T..."
13,12,Zohair Rizvi,NaN,NaN,NaN,Zohairpk@gmail.com,0333-2011181,NaN,NaN,NaN
14,13,Syed Zafaryab Abbas,NaN,NaN,NaN,muhammadzafaryab@gmail.com,0302-2710803,NaN,NaN,NaN
15,14,Moin UL Hassan,NaN,NaN,NaN,moinmono2@gmail.com,0322-6264804,NaN,NaN,NaN
16,15,Muhammad Ali Naqvi,28th March,Amjad Ali Naqvi,Farzana Amjad,ali.naqvi@ciphertronix.com,0334-0765855,NaN,NaN,House#R-1 Alhabib Society Gulistan e Jauhar ...

In [10]:
laptop = pd.read_csv("laptop.csv",encoding="latin1")

In [11]:
laptop

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price (Euros)
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94"
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00"
3,Apple,MacBook Pro,Ultrabook,"15.4""",IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,"2537,45"
4,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,"1803,60"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,"14.0""",IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows,10,1.8kg,"638,00"
1299,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,"13.3""",IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows,10,1.3kg,"1499,00"
1300,Lenovo,IdeaPad 100S-14IBR,Notebook,"14.0""",1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows,10,1.5kg,"229,00"
1301,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,"15.6""",1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows,10,2.19kg,"764,00"
1302,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,"15.6""",1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows,10,2.2kg,"369,00"

In [12]:
laptop.shape

(1303, 13)

In [13]:
data = {
    "Name":['Mehdi','Abbas','Murtaza'],
    "Age":[17,17,15],
    "City":['Munich','Madrid','Karachi']
}

In [14]:
data = pd.DataFrame(data)

In [15]:
data

      Name  Age     City
0    Mehdi   17   Munich
1    Abbas   17   Madrid
2  Murtaza   15  Karachi

In [16]:
data.to_csv("data.csv")